[default]
SECRET_KEY = 'secret'
SQLALCHEMY_TRACK_MODIFICATIONS = false
UPLOAD_FOLDER = 'uploads'
EXTENSIONS = ['app.extensions:init_app', 'mvc_flask:FlaskMVC']

[development]
SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:postgres@db/betravel_dev'

[testing]
SQLALCHEMY_DATABASE_URI = 'sqlite:///'
WTF_CSRF_ENABLED = false