"""empty message

Revision ID: 80347da19d4e
Revises: 50e71ce6293e
Create Date: 2022-09-30 08:15:44.933405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80347da19d4e'
down_revision = '50e71ce6293e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
